name: manager_web
description: WorkFlow Manager Web Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  excel: ^4.0.6
  fl_chart: ^0.70.2
  table_calendar: ^3.2.0
  core:
    path: ../../packages/core
  supabase_client:
    path: ../../packages/supabase_client
  ui_components:
    path: ../../packages/ui_components
  uuid: ^4.5.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
